#!/bin/sh

clear
echo " "
echo "Selamat Datang di Vm Debian 10"
echo "Silakan gunakan dengan bijak."
echo " "
echo "Author Vm: Sofian Nasution"
echo "Contact Person:"
echo "  • Telegram: t.me/username"
echo "  • WhatsApp: wa.me/62xxxxxxxxx"
echo "  • GitHub: github.com/username"
echo " "
echo "Bantuan, kritik, dan saran, silakan hubungi saya."
echo " "
